### ISSUE TITLE
math/overflow (similar to "loop" but based on "remainder")

### ISSUE THREAD

**Issue by millermedeiros** [mout/mout#106]
Sometimes I need this feature but never spent enough time to come up with a clean implementation.

The logic behind it is that if the `value > max || value < min` it should calculate the "remainder of the overflow".

```js
// between 0 and 20 there are 20 numbers
// 22 is greater than 20
// result = 0 + (22 - 20)
result = overflow(22, 0, 20); // 2

// between 10 and 20 there are 10 numbers.
// 32 is greater than 20
// result = 10 + ((32 - 10) % 21)
overflow(32, 10, 20); // 12

// between -5 and 5 there are 10 numbers
// -7 is smaller than -5
// result = 5 - (abs(-7) - abs(-5))
overflow(-7, -5, 5); // 3
```

more examples:

```js
overflow(22,  0, 20); // 2
overflow(32,  0, 20); // 12
overflow(-2,  0, 20); // 18
overflow(-10, 0, 20); // 10

overflow(22, 10, 20); // 12
overflow(32, 10, 20); // 12

overflow(7,  -5, 5);  // -3
overflow(10, -5, 5);  // 0
overflow(12, -5, 5);  // 2
overflow(15, -5, 5);  // 5
overflow(-7, -5, 5);  // 3
```

I have this naive implementation on my current project:

```js
function overflowMonth(monthIndex){
    // similar to mout/math/loop but overflows remainder
    var modulo = monthIndex % 12;
    if (monthIndex < 0) {
        monthIndex = 12 + modulo;
    } else if (monthIndex >= 12) {
        monthIndex = modulo;
    }
    return monthIndex;
}
```

so that I can get a date in the future/past like:

```js
var currentMonth = (new Date).getMonth(); // 5 (June)
// 14 months in the future
var futureMonth = overflowMonth( currentMonth + 14 ); // 7 (August)
// 32 months ago
var pastMonth = overflowMonth( currentMonth - 32 ); // 9 (October)
```

But it surely gets more complicated when you add the "dynamic" `min` and `max` and need to support negative/positive numbers - I remember once writing a solution that worked for all cases but was very ugly (can't find it at the moment)... - it's also important to note that I've never seen a method similar to this on any lib, maybe I'm the only one who finds it useful.

Pull requests are highly appreciated.

**Comment by MathiasPaumgarten** [comment]
Hey guys, @millermedeiros just pointed this thread out to me. I forgot about it, but I recall seeing it. I have created a functioning PR, but I called the method `mout/math/wrap`, but I think `overflow` is pretty good too. 
My approach ends up being very close to @mindoftea's solution. Maybe we should move the discussion to it over here: #241

**Comment by MathiasPaumgarten** [comment]
Closing this thread. All further conversation on this is moved to #241
