### ISSUE TITLE
v1.0 release

### ISSUE THREAD

**Issue by millermedeiros** [mout/mout#11]
I think we should try to release v1.0 in the next 2-3 months. Some things I would like to see done:

 - [ ] double check API consistency (names, arguments, etc)
 - [ ] remove methods that are not generic enough (not sure if we have any)
 - [ ] add missing features from underscore.js/lodash/mootools/prootype.js/dojo (low priority, more to make sure the current method names makes sense and that we won't have conflicts down the road)

The goal of the v1.0 release is to say that the API can be considered *stable*, after v1.0 we should avoid breaking changes as much as possible, so the sooner we *fix* these things the better. We can always add more features and refactor the code later.

**Comment by sheerun** [comment]
Hey, maybe release mout 1.0 without awesome features, just to show maturity be semver friendly.

According to semver any bump < 1.0 can be a breaking change..

Then in 2.0 you could include appropriate improvements. Don't be afraid of major bump.

**Comment by MathiasPaumgarten** [comment]
@sheerun agreed! [v1.0.0](https://www.npmjs.com/package/mout)
