### ISSUE TITLE
Strange / unexpected behavior of object.merge

### ISSUE THREAD

**Issue by leider** [mout/mout#203]
The following test fails, because a property with a value of 'undefined' is treated differently from an undefined property. This is very misleading. It finally leads to a build problem in tools using bower. See https://github.com/rse/grunt-bower-install-simple/pull/8

```javascript
        it('should ignore "undefined" properties when merging', function () {

          var obj1 = {a: 0, b: 3};
          var obj2 = {a: 2};
          var obj3 = {a: 2, b: undefined};
          
          var out = {a: 2, b: 3};
          
          expect( merge(obj1, obj2)).toEqual( out );
          expect( merge(obj1, obj3)).toEqual( out );
        });
```      
The second `expect` will fail.

You can clearly state: "works as specified" and closing this issue. Then a few words in the docs / examples would be helpful.

**Comment by satazor** [comment]
I think the current behaviour makes more sense but yes, the documentation should perhaps state that properties with nullish values (null/undefined) are treated like any other property value.
