### ISSUE TITLE
Feature request / 1.0 change - object.getOwn

### ISSUE THREAD

**Issue by sheerun** [mout/mout#204]
Mout currently has `hasOwn` and `get`, but lacks `getOwn` that ignores special properties like `constructor`.

While changing all `get` to `getOwn` is an easy change, sprinkling `hasOwn` all over the place is hard.

Or maybe change bahavior of `get` to return only own properties?

See related issue: https://github.com/bower/bower/issues/978

**Comment by millermedeiros** [comment]
see #11
