### ISSUE TITLE
Number `abbreviate` docs custom dictionary is incorrect

### ISSUE THREAD

**Issue by chrisjhoughton** [mout/mout#218]
In the docs it suggests you can pass a custom dictionary by using the following for `abbreviate`:

```js
var _ptbrDict = {
    thousands : ' mil',
    millions : ' Mi',
    billions : ' Bi'
};
```

Looking in the [source](https://github.com/mout/mout/blob/v0.11.0/src/number/abbreviate.js), the dictionary is actually:

```js
var _defaultDict = {
   thousand : 'K',
   million : 'M',
   billion : 'B'
};
```

**Comment by millermedeiros** [comment]
thanks! updated on master, but should only really be published on next release.

**Comment by chrisjhoughton** [comment]
Nice one, hardly urgent but thought I'd flag it after all my abbreviations turned to `NaN`! Awesome module.
