### ISSUE TITLE
How does use MOUT with JSPM

### ISSUE THREAD

**Issue by jdwillemse** [mout/mout#236]
I cannot figure out how to import a MOUT module into my file using JSPM. Is it possible?

I asked this on [Stackoverflow](http://stackoverflow.com/questions/31607252/using-mout-js-module-with-jspm) too.

**Comment by satazor** [comment]
Cc @guybedford

**Comment by jdwillemse** [comment]
Someone answered my questions perfectly:

jspm install npm:mout
import equals from 'mout/array/equals';
