### ISSUE TITLE
v1.2.0 breaks with node?

### ISSUE THREAD

**Issue by Trott** [mout/mout#261]
Looks like 1.2.0 was perhaps published without running `nodefy`? Am I wrong? It seems like 1.2.0 breaks `esformatter` and other modules?

**Comment by greengumby** [comment]
Seems like the latest release has broken bower?

nternal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'mout/lang'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by Trott** [comment]
Quickest fix for end users is probably to uninstall mout@1.2.0 and install mout@1.1.0. However another fix is `( cd node_modules/mout && npx nodefy -o . 'src/**.js' )`. That will run the step that I believe was missed before publishing 1.2.0. Best of course would be for a maintainer to run `nodefy` and publish 1.2.1 promptly.

**Comment by hzyhbk** [comment]
I found the same problem,  because the 1.2.0 package was released without compiling.

**Comment by sumanthio** [comment]
How do we solve this if the error is from `mout` in a circular dependancy? wiredep, bower-config so many packages use mout?

**Comment by JoseLawrence** [comment]
Same issue here, please! 

`Error: Cannot find module 'mout/lang'`

**Comment by Casana** [comment]
We are facing same issue with **v1.2.0**, we are downgrading to v1.1.0 which works fine.

**Comment by roboshoes** [comment]
Sorry everybody. Deployment issue. Use 1.1.0 until I push a fix today.

**Comment by roboshoes** [comment]
[1.2.1](https://www.npmjs.com/package/mout) was pushed. Preliminary tests show that it deployed correctly. Please feel free to upgrade to this version. I will close this issue after a bit of further testing and improving the deployment process.

**Comment by sharif-elshobkshy** [comment]
Have several sites broken due to this issue.

Ohh @roboshoes you little devil

**Comment by roboshoes** [comment]
😈

@sharif-elshobkshy is 1.2.1 working for you though?

**Comment by alejo-moreno** [comment]
Might be a good time to remember this https://twitter.com/cassidoo/status/1154809678607446016
Anyway, everything is good now 👍

**Comment by sharif-elshobkshy** [comment]
@roboshoes Yes. Since to be working fine now.

Have a good weekend.

PD: Please don't deploy anything during the weekend :p

**Comment by roboshoes** [comment]
Haha, Fair enough!

**Comment by Trott** [comment]
This seems fixed. I'm going to close this, but if you think that's the wrong move, feel free to re-open.
