### ISSUE TITLE
Prototype Pollution

### ISSUE THREAD

**Issue by andrew-itscript** [mout/mout#273]
![Desktop 2021-04-08 11-15-24](https://user-images.githubusercontent.com/29883742/113967778-ecf72d80-985b-11eb-8b60-d4a4337786b9.png)
https://app.snyk.io/test/npm/mout

**Comment by Eido95** [comment]
This vulnerability [seems to be here since the beginning](https://snyk.io/vuln/npm:mout), fix will be much appreciated @roboshoes

**Comment by pieceofsoft** [comment]
Hi, is there a chance to release the fix during August?

**Comment by cameronperera** [comment]
Hi! Is there currently a plan to release a fix for this issue? @roboshoes

**Comment by amit199309** [comment]
Hi @roboshoes , 
We are also getting **"Prototype Pollution"** vulnerability issue and this PR already having the fix for same, so could you please plan to merge and release this fix. Thank you
