### ISSUE TITLE
Is the 2.0 TS version abandoned

### ISSUE THREAD

**Issue by joshua1** [mout/mout#277]
Is the 2.0 alpha version with es6 and typescript support abandoned? It would be really helpful to get that version out. It's a whole year already. Also how can I contribute to getting that version out

**Comment by roboshoes** [comment]
It has been. I'm not opposed to a version 2 from the community but as of my knowledge, nobody is working on it right now. Full type support would be nice but it would be a major overhaul and not backward compatible.

**Comment by niksy** [comment]
I’ve just stumbled on this issue. Really sorry to hear that this has been abandoned. I’ve tried my best to make first migration effort, but then it kind of was left in that state, and from my side I was too busy to get on additional work :/
