### ISSUE TITLE
CHANGELOG.md and release tags out of date

### ISSUE THREAD

**Issue by christi-square** [mout/mout#280]
The CHANGELOG is missing changes for release versions 1.2.2 and 1.2.3 and contains changes for non-existent version 1.1.1. As no comments were added on the release versions, it is very helpful to have a changelog to determine what changes were made in a version to easily enable upgrade testing. 

It also looks like 1.2.1 was released on npm but has no release tag (or changelog). 1.2.2 was _not_ released on npm and has a release tag.

Alpha branch 2.0.0 also does not have any CHANGELOG updates.

**Comment by roboshoes** [comment]
Thanks for the heads up. Since I just pushed today the 1.2.4 I updated the changelog. For at least this version. 

The v2 alpha is likely abandoned at this point as the library achieved majority and won't see another big change.
