### ISSUE TITLE
ES6 (Harmony) math methods

### ISSUE THREAD

**Issue by millermedeiros** [mout/mout#43]
harmony adds a series of new Math methods, maybe we should add them as well:
- http://people.mozilla.org/~jorendorff/es6-draft.html#sec-15.8
- http://wiki.ecmascript.org/doku.php?id=harmony:more_math_functions

note that `sign` is currently inside the [number package](http://moutjs.com/docs/latest/number.html) on mout, maybe we should change that as well.

PS: this is low priority and I would probably defer it to a later version.

**Comment by MathiasPaumgarten** [comment]
I think as we come closer to self updating browsers, this is starting to become a bit of a niche value of mout to simply stub out features. 

I think the real value comes from features that aren't provided by browsers.
